import type { Metadata } from "next";
import { Raleway, Roboto } from "next/font/google";
import "@/styles/global.css";
import Navbar from "@/components/Navbar";

const ralewayFont = Raleway({
	variable: "--font-raleway",
	subsets: ["latin"],
});

const robotoFont = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${ralewayFont.variable} ${robotoFont.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<Navbar />
				{children}
			</body>
		</html>
	);
}
